export type Country = { code: string; flag: string; name: string; dial: string }

export const COUNTRIES: Country[] = [
  { code: 'AF', flag: '🇦🇫', name: 'Afghanistan',                  dial: '+93'    },
  { code: 'AL', flag: '🇦🇱', name: 'Albania',                      dial: '+355'   },
  { code: 'DZ', flag: '🇩🇿', name: 'Algeria',                      dial: '+213'   },
  { code: 'AD', flag: '🇦🇩', name: 'Andorra',                      dial: '+376'   },
  { code: 'AO', flag: '🇦🇴', name: 'Angola',                       dial: '+244'   },
  { code: 'AG', flag: '🇦🇬', name: 'Antigua and Barbuda',          dial: '+1-268' },
  { code: 'AR', flag: '🇦🇷', name: 'Argentina',                    dial: '+54'    },
  { code: 'AM', flag: '🇦🇲', name: 'Armenia',                      dial: '+374'   },
  { code: 'AU', flag: '🇦🇺', name: 'Australia',                    dial: '+61'    },
  { code: 'AT', flag: '🇦🇹', name: 'Austria',                      dial: '+43'    },
  { code: 'AZ', flag: '🇦🇿', name: 'Azerbaijan',                   dial: '+994'   },
  { code: 'BS', flag: '🇧🇸', name: 'Bahamas',                      dial: '+1-242' },
  { code: 'BH', flag: '🇧🇭', name: 'Bahrain',                      dial: '+973'   },
  { code: 'BD', flag: '🇧🇩', name: 'Bangladesh',                   dial: '+880'   },
  { code: 'BB', flag: '🇧🇧', name: 'Barbados',                     dial: '+1-246' },
  { code: 'BY', flag: '🇧🇾', name: 'Belarus',                      dial: '+375'   },
  { code: 'BE', flag: '🇧🇪', name: 'Belgium',                      dial: '+32'    },
  { code: 'BZ', flag: '🇧🇿', name: 'Belize',                       dial: '+501'   },
  { code: 'BJ', flag: '🇧🇯', name: 'Benin',                        dial: '+229'   },
  { code: 'BT', flag: '🇧🇹', name: 'Bhutan',                       dial: '+975'   },
  { code: 'BO', flag: '🇧🇴', name: 'Bolivia',                      dial: '+591'   },
  { code: 'BA', flag: '🇧🇦', name: 'Bosnia and Herzegovina',       dial: '+387'   },
  { code: 'BW', flag: '🇧🇼', name: 'Botswana',                     dial: '+267'   },
  { code: 'BR', flag: '🇧🇷', name: 'Brazil',                       dial: '+55'    },
  { code: 'BN', flag: '🇧🇳', name: 'Brunei',                       dial: '+673'   },
  { code: 'BG', flag: '🇧🇬', name: 'Bulgaria',                     dial: '+359'   },
  { code: 'BF', flag: '🇧🇫', name: 'Burkina Faso',                 dial: '+226'   },
  { code: 'BI', flag: '🇧🇮', name: 'Burundi',                      dial: '+257'   },
  { code: 'CV', flag: '🇨🇻', name: 'Cabo Verde',                   dial: '+238'   },
  { code: 'KH', flag: '🇰🇭', name: 'Cambodia',                     dial: '+855'   },
  { code: 'CM', flag: '🇨🇲', name: 'Cameroon',                     dial: '+237'   },
  { code: 'CA', flag: '🇨🇦', name: 'Canada',                       dial: '+1'     },
  { code: 'CF', flag: '🇨🇫', name: 'Central African Republic',     dial: '+236'   },
  { code: 'TD', flag: '🇹🇩', name: 'Chad',                         dial: '+235'   },
  { code: 'CL', flag: '🇨🇱', name: 'Chile',                        dial: '+56'    },
  { code: 'CN', flag: '🇨🇳', name: 'China',                        dial: '+86'    },
  { code: 'CO', flag: '🇨🇴', name: 'Colombia',                     dial: '+57'    },
  { code: 'KM', flag: '🇰🇲', name: 'Comoros',                      dial: '+269'   },
  { code: 'CG', flag: '🇨🇬', name: 'Congo',                        dial: '+242'   },
  { code: 'CD', flag: '🇨🇩', name: 'Congo (DRC)',                  dial: '+243'   },
  { code: 'CR', flag: '🇨🇷', name: 'Costa Rica',                   dial: '+506'   },
  { code: 'CI', flag: '🇨🇮', name: "Côte d'Ivoire",               dial: '+225'   },
  { code: 'HR', flag: '🇭🇷', name: 'Croatia',                      dial: '+385'   },
  { code: 'CU', flag: '🇨🇺', name: 'Cuba',                         dial: '+53'    },
  { code: 'CY', flag: '🇨🇾', name: 'Cyprus',                       dial: '+357'   },
  { code: 'CZ', flag: '🇨🇿', name: 'Czech Republic',               dial: '+420'   },
  { code: 'DK', flag: '🇩🇰', name: 'Denmark',                      dial: '+45'    },
  { code: 'DJ', flag: '🇩🇯', name: 'Djibouti',                     dial: '+253'   },
  { code: 'DM', flag: '🇩🇲', name: 'Dominica',                     dial: '+1-767' },
  { code: 'DO', flag: '🇩🇴', name: 'Dominican Republic',           dial: '+1-809' },
  { code: 'EC', flag: '🇪🇨', name: 'Ecuador',                      dial: '+593'   },
  { code: 'EG', flag: '🇪🇬', name: 'Egypt',                        dial: '+20'    },
  { code: 'SV', flag: '🇸🇻', name: 'El Salvador',                  dial: '+503'   },
  { code: 'GQ', flag: '🇬🇶', name: 'Equatorial Guinea',            dial: '+240'   },
  { code: 'ER', flag: '🇪🇷', name: 'Eritrea',                      dial: '+291'   },
  { code: 'EE', flag: '🇪🇪', name: 'Estonia',                      dial: '+372'   },
  { code: 'SZ', flag: '🇸🇿', name: 'Eswatini',                     dial: '+268'   },
  { code: 'ET', flag: '🇪🇹', name: 'Ethiopia',                     dial: '+251'   },
  { code: 'FJ', flag: '🇫🇯', name: 'Fiji',                         dial: '+679'   },
  { code: 'FI', flag: '🇫🇮', name: 'Finland',                      dial: '+358'   },
  { code: 'FR', flag: '🇫🇷', name: 'France',                       dial: '+33'    },
  { code: 'GA', flag: '🇬🇦', name: 'Gabon',                        dial: '+241'   },
  { code: 'GM', flag: '🇬🇲', name: 'Gambia',                       dial: '+220'   },
  { code: 'GE', flag: '🇬🇪', name: 'Georgia',                      dial: '+995'   },
  { code: 'DE', flag: '🇩🇪', name: 'Germany',                      dial: '+49'    },
  { code: 'GH', flag: '🇬🇭', name: 'Ghana',                        dial: '+233'   },
  { code: 'GR', flag: '🇬🇷', name: 'Greece',                       dial: '+30'    },
  { code: 'GD', flag: '🇬🇩', name: 'Grenada',                      dial: '+1-473' },
  { code: 'GT', flag: '🇬🇹', name: 'Guatemala',                    dial: '+502'   },
  { code: 'GN', flag: '🇬🇳', name: 'Guinea',                       dial: '+224'   },
  { code: 'GW', flag: '🇬🇼', name: 'Guinea-Bissau',                dial: '+245'   },
  { code: 'GY', flag: '🇬🇾', name: 'Guyana',                       dial: '+592'   },
  { code: 'HT', flag: '🇭🇹', name: 'Haiti',                        dial: '+509'   },
  { code: 'HN', flag: '🇭🇳', name: 'Honduras',                     dial: '+504'   },
  { code: 'HU', flag: '🇭🇺', name: 'Hungary',                      dial: '+36'    },
  { code: 'IS', flag: '🇮🇸', name: 'Iceland',                      dial: '+354'   },
  { code: 'IN', flag: '🇮🇳', name: 'India',                        dial: '+91'    },
  { code: 'ID', flag: '🇮🇩', name: 'Indonesia',                    dial: '+62'    },
  { code: 'IR', flag: '🇮🇷', name: 'Iran',                         dial: '+98'    },
  { code: 'IQ', flag: '🇮🇶', name: 'Iraq',                         dial: '+964'   },
  { code: 'IE', flag: '🇮🇪', name: 'Ireland',                      dial: '+353'   },
  { code: 'IL', flag: '🇮🇱', name: 'Israel',                       dial: '+972'   },
  { code: 'IT', flag: '🇮🇹', name: 'Italy',                        dial: '+39'    },
  { code: 'JM', flag: '🇯🇲', name: 'Jamaica',                      dial: '+1-876' },
  { code: 'JP', flag: '🇯🇵', name: 'Japan',                        dial: '+81'    },
  { code: 'JO', flag: '🇯🇴', name: 'Jordan',                       dial: '+962'   },
  { code: 'KZ', flag: '🇰🇿', name: 'Kazakhstan',                   dial: '+7'     },
  { code: 'KE', flag: '🇰🇪', name: 'Kenya',                        dial: '+254'   },
  { code: 'KI', flag: '🇰🇮', name: 'Kiribati',                     dial: '+686'   },
  { code: 'KW', flag: '🇰🇼', name: 'Kuwait',                       dial: '+965'   },
  { code: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan',                   dial: '+996'   },
  { code: 'LA', flag: '🇱🇦', name: 'Laos',                         dial: '+856'   },
  { code: 'LV', flag: '🇱🇻', name: 'Latvia',                       dial: '+371'   },
  { code: 'LB', flag: '🇱🇧', name: 'Lebanon',                      dial: '+961'   },
  { code: 'LS', flag: '🇱🇸', name: 'Lesotho',                      dial: '+266'   },
  { code: 'LR', flag: '🇱🇷', name: 'Liberia',                      dial: '+231'   },
  { code: 'LY', flag: '🇱🇾', name: 'Libya',                        dial: '+218'   },
  { code: 'LI', flag: '🇱🇮', name: 'Liechtenstein',                dial: '+423'   },
  { code: 'LT', flag: '🇱🇹', name: 'Lithuania',                    dial: '+370'   },
  { code: 'LU', flag: '🇱🇺', name: 'Luxembourg',                   dial: '+352'   },
  { code: 'MG', flag: '🇲🇬', name: 'Madagascar',                   dial: '+261'   },
  { code: 'MW', flag: '🇲🇼', name: 'Malawi',                       dial: '+265'   },
  { code: 'MY', flag: '🇲🇾', name: 'Malaysia',                     dial: '+60'    },
  { code: 'MV', flag: '🇲🇻', name: 'Maldives',                     dial: '+960'   },
  { code: 'ML', flag: '🇲🇱', name: 'Mali',                         dial: '+223'   },
  { code: 'MT', flag: '🇲🇹', name: 'Malta',                        dial: '+356'   },
  { code: 'MH', flag: '🇲🇭', name: 'Marshall Islands',             dial: '+692'   },
  { code: 'MR', flag: '🇲🇷', name: 'Mauritania',                   dial: '+222'   },
  { code: 'MU', flag: '🇲🇺', name: 'Mauritius',                    dial: '+230'   },
  { code: 'MX', flag: '🇲🇽', name: 'Mexico',                       dial: '+52'    },
  { code: 'FM', flag: '🇫🇲', name: 'Micronesia',                   dial: '+691'   },
  { code: 'MD', flag: '🇲🇩', name: 'Moldova',                      dial: '+373'   },
  { code: 'MC', flag: '🇲🇨', name: 'Monaco',                       dial: '+377'   },
  { code: 'MN', flag: '🇲🇳', name: 'Mongolia',                     dial: '+976'   },
  { code: 'ME', flag: '🇲🇪', name: 'Montenegro',                   dial: '+382'   },
  { code: 'MA', flag: '🇲🇦', name: 'Morocco',                      dial: '+212'   },
  { code: 'MZ', flag: '🇲🇿', name: 'Mozambique',                   dial: '+258'   },
  { code: 'MM', flag: '🇲🇲', name: 'Myanmar',                      dial: '+95'    },
  { code: 'NA', flag: '🇳🇦', name: 'Namibia',                      dial: '+264'   },
  { code: 'NR', flag: '🇳🇷', name: 'Nauru',                        dial: '+674'   },
  { code: 'NP', flag: '🇳🇵', name: 'Nepal',                        dial: '+977'   },
  { code: 'NL', flag: '🇳🇱', name: 'Netherlands',                  dial: '+31'    },
  { code: 'NZ', flag: '🇳🇿', name: 'New Zealand',                  dial: '+64'    },
  { code: 'NI', flag: '🇳🇮', name: 'Nicaragua',                    dial: '+505'   },
  { code: 'NE', flag: '🇳🇪', name: 'Niger',                        dial: '+227'   },
  { code: 'NG', flag: '🇳🇬', name: 'Nigeria',                      dial: '+234'   },
  { code: 'NO', flag: '🇳🇴', name: 'Norway',                       dial: '+47'    },
  { code: 'OM', flag: '🇴🇲', name: 'Oman',                         dial: '+968'   },
  { code: 'PK', flag: '🇵🇰', name: 'Pakistan',                     dial: '+92'    },
  { code: 'PW', flag: '🇵🇼', name: 'Palau',                        dial: '+680'   },
  { code: 'PA', flag: '🇵🇦', name: 'Panama',                       dial: '+507'   },
  { code: 'PG', flag: '🇵🇬', name: 'Papua New Guinea',             dial: '+675'   },
  { code: 'PY', flag: '🇵🇾', name: 'Paraguay',                     dial: '+595'   },
  { code: 'PE', flag: '🇵🇪', name: 'Peru',                         dial: '+51'    },
  { code: 'PH', flag: '🇵🇭', name: 'Philippines',                  dial: '+63'    },
  { code: 'PL', flag: '🇵🇱', name: 'Poland',                       dial: '+48'    },
  { code: 'PT', flag: '🇵🇹', name: 'Portugal',                     dial: '+351'   },
  { code: 'QA', flag: '🇶🇦', name: 'Qatar',                        dial: '+974'   },
  { code: 'RO', flag: '🇷🇴', name: 'Romania',                      dial: '+40'    },
  { code: 'RU', flag: '🇷🇺', name: 'Russia',                       dial: '+7'     },
  { code: 'RW', flag: '🇷🇼', name: 'Rwanda',                       dial: '+250'   },
  { code: 'KN', flag: '🇰🇳', name: 'Saint Kitts and Nevis',        dial: '+1-869' },
  { code: 'LC', flag: '🇱🇨', name: 'Saint Lucia',                  dial: '+1-758' },
  { code: 'VC', flag: '🇻🇨', name: 'Saint Vincent and Grenadines', dial: '+1-784' },
  { code: 'WS', flag: '🇼🇸', name: 'Samoa',                        dial: '+685'   },
  { code: 'SM', flag: '🇸🇲', name: 'San Marino',                   dial: '+378'   },
  { code: 'ST', flag: '🇸🇹', name: 'São Tomé and Príncipe',        dial: '+239'   },
  { code: 'SA', flag: '🇸🇦', name: 'Saudi Arabia',                 dial: '+966'   },
  { code: 'SN', flag: '🇸🇳', name: 'Senegal',                      dial: '+221'   },
  { code: 'RS', flag: '🇷🇸', name: 'Serbia',                       dial: '+381'   },
  { code: 'SC', flag: '🇸🇨', name: 'Seychelles',                   dial: '+248'   },
  { code: 'SL', flag: '🇸🇱', name: 'Sierra Leone',                 dial: '+232'   },
  { code: 'SG', flag: '🇸🇬', name: 'Singapore',                    dial: '+65'    },
  { code: 'SK', flag: '🇸🇰', name: 'Slovakia',                     dial: '+421'   },
  { code: 'SI', flag: '🇸🇮', name: 'Slovenia',                     dial: '+386'   },
  { code: 'SB', flag: '🇸🇧', name: 'Solomon Islands',              dial: '+677'   },
  { code: 'SO', flag: '🇸🇴', name: 'Somalia',                      dial: '+252'   },
  { code: 'ZA', flag: '🇿🇦', name: 'South Africa',                 dial: '+27'    },
  { code: 'SS', flag: '🇸🇸', name: 'South Sudan',                  dial: '+211'   },
  { code: 'ES', flag: '🇪🇸', name: 'Spain',                        dial: '+34'    },
  { code: 'LK', flag: '🇱🇰', name: 'Sri Lanka',                    dial: '+94'    },
  { code: 'SD', flag: '🇸🇩', name: 'Sudan',                        dial: '+249'   },
  { code: 'SR', flag: '🇸🇷', name: 'Suriname',                     dial: '+597'   },
  { code: 'SE', flag: '🇸🇪', name: 'Sweden',                       dial: '+46'    },
  { code: 'CH', flag: '🇨🇭', name: 'Switzerland',                  dial: '+41'    },
  { code: 'SY', flag: '🇸🇾', name: 'Syria',                        dial: '+963'   },
  { code: 'TW', flag: '🇹🇼', name: 'Taiwan',                       dial: '+886'   },
  { code: 'TJ', flag: '🇹🇯', name: 'Tajikistan',                   dial: '+992'   },
  { code: 'TZ', flag: '🇹🇿', name: 'Tanzania',                     dial: '+255'   },
  { code: 'TH', flag: '🇹🇭', name: 'Thailand',                     dial: '+66'    },
  { code: 'TL', flag: '🇹🇱', name: 'Timor-Leste',                  dial: '+670'   },
  { code: 'TG', flag: '🇹🇬', name: 'Togo',                         dial: '+228'   },
  { code: 'TO', flag: '🇹🇴', name: 'Tonga',                        dial: '+676'   },
  { code: 'TT', flag: '🇹🇹', name: 'Trinidad and Tobago',          dial: '+1-868' },
  { code: 'TN', flag: '🇹🇳', name: 'Tunisia',                      dial: '+216'   },
  { code: 'TR', flag: '🇹🇷', name: 'Turkey',                       dial: '+90'    },
  { code: 'TM', flag: '🇹🇲', name: 'Turkmenistan',                 dial: '+993'   },
  { code: 'TV', flag: '🇹🇻', name: 'Tuvalu',                       dial: '+688'   },
  { code: 'UG', flag: '🇺🇬', name: 'Uganda',                       dial: '+256'   },
  { code: 'UA', flag: '🇺🇦', name: 'Ukraine',                      dial: '+380'   },
  { code: 'AE', flag: '🇦🇪', name: 'United Arab Emirates',         dial: '+971'   },
  { code: 'GB', flag: '🇬🇧', name: 'United Kingdom',               dial: '+44'    },
  { code: 'US', flag: '🇺🇸', name: 'United States',                dial: '+1'     },
  { code: 'UY', flag: '🇺🇾', name: 'Uruguay',                      dial: '+598'   },
  { code: 'UZ', flag: '🇺🇿', name: 'Uzbekistan',                   dial: '+998'   },
  { code: 'VU', flag: '🇻🇺', name: 'Vanuatu',                      dial: '+678'   },
  { code: 'VE', flag: '🇻🇪', name: 'Venezuela',                    dial: '+58'    },
  { code: 'VN', flag: '🇻🇳', name: 'Vietnam',                      dial: '+84'    },
  { code: 'YE', flag: '🇾🇪', name: 'Yemen',                        dial: '+967'   },
  { code: 'ZM', flag: '🇿🇲', name: 'Zambia',                       dial: '+260'   },
  { code: 'ZW', flag: '🇿🇼', name: 'Zimbabwe',                     dial: '+263'   },
]

export function findCountry(codeOrName: string): Country | undefined {
  const q = codeOrName.toUpperCase()
  return COUNTRIES.find(c => c.code === q || c.name.toUpperCase() === q)
}
