export const ALL_PERMISSIONS = [
  'scans.create',
  'scans.read',
  'scans.update',
  'scans.archive',
  'findings.read',
  'findings.update',
  'findings.archive',
  'assets.create',
  'assets.read',
  'assets.update',
  'assets.archive',
  'reports.read.scan',
  'reports.read.organizational',
  'reports.read.executive',
  'reports.read.board',
  'reports.generate',
  'reports.export',
  'exports.create',
  'exports.read',
  'remediation.read',
  'remediation.update',
  'remediation.batches.create',
  'remediation.batches.read',
  'remediation.batches.update',
  'remediation.batches.archive',
  'remediation.tasks.read',
  'remediation.tasks.update',
  'remediation.ai_assist',
  'integrations.jira',
  'audit.read',
  'team.read',
  'team.invite',
] as const

export type Permission = typeof ALL_PERMISSIONS[number]

export const ADMIN_DEFAULTS: Record<Permission, boolean> = {
  'scans.create':               true,
  'scans.read':                 true,
  'scans.update':               true,
  'scans.archive':              true,
  'findings.read':              true,
  'findings.update':            true,
  'findings.archive':           true,
  'assets.create':              true,
  'assets.read':                true,
  'assets.update':              true,
  'assets.archive':             true,
  'reports.read.scan':          true,
  'reports.read.organizational': true,
  'reports.read.executive':     false,
  'reports.read.board':         false,
  'reports.generate':           true,
  'reports.export':             true,
  'exports.create':             true,
  'exports.read':               true,
  'remediation.read':           true,
  'remediation.update':         true,
  'remediation.batches.create':  true,
  'remediation.batches.read':    true,
  'remediation.batches.update':  true,
  'remediation.batches.archive': true,
  'remediation.tasks.read':      true,
  'remediation.tasks.update':    true,
  'remediation.ai_assist':       true,
  'integrations.jira':           false,
  'audit.read':                 true,
  'team.read':                  true,
  'team.invite':                false,
}

export const MEMBER_DEFAULTS: Record<Permission, boolean> = {
  'scans.create':               false,
  'scans.read':                 false,
  'scans.update':               false,
  'scans.archive':              false,
  'findings.read':              false,
  'findings.update':            false,
  'findings.archive':           false,
  'assets.create':              false,
  'assets.read':                false,
  'assets.update':              false,
  'assets.archive':             false,
  'reports.read.scan':          false,
  'reports.read.organizational': false,
  'reports.read.executive':     false,
  'reports.read.board':         false,
  'reports.generate':           false,
  'reports.export':             false,
  'exports.create':             false,
  'exports.read':               false,
  'remediation.read':           false,
  'remediation.update':         false,
  'remediation.batches.create':  false,
  'remediation.batches.read':    false,
  'remediation.batches.update':  false,
  'remediation.batches.archive': false,
  'remediation.tasks.read':      false,
  'remediation.tasks.update':    false,
  'remediation.ai_assist':       false,
  'integrations.jira':           false,
  'audit.read':                 false,
  'team.read':                  false,
  'team.invite':                false,
}

export const VIEWER_DEFAULTS: Record<Permission, boolean> = {
  'scans.create':                false,
  'scans.read':                  false,
  'scans.update':                false,
  'scans.archive':               false,
  'findings.read':               true,
  'findings.update':             false,
  'findings.archive':            false,
  'assets.create':               false,
  'assets.read':                 true,
  'assets.update':               false,
  'assets.archive':              false,
  'reports.read.scan':           true,
  'reports.read.organizational': true,
  'reports.read.executive':      false,
  'reports.read.board':          false,
  'reports.generate':            false,
  'reports.export':              false,
  'exports.create':              false,
  'exports.read':                true,
  'remediation.read':            true,
  'remediation.update':          false,
  'remediation.batches.create':  false,
  'remediation.batches.read':    false,
  'remediation.batches.update':  false,
  'remediation.batches.archive': false,
  'remediation.tasks.read':      false,
  'remediation.tasks.update':    false,
  'remediation.ai_assist':       false,
  'integrations.jira':           false,
  'audit.read':                  false,
  'team.read':                   false,
  'team.invite':                 false,
}

export const DEVELOPER_DEFAULTS: Record<Permission, boolean> = {
  'scans.create':                false,
  'scans.read':                  true,
  'scans.update':                false,
  'scans.archive':               false,
  'findings.read':               true,
  'findings.update':             false,
  'findings.archive':            false,
  'assets.create':               false,
  'assets.read':                 true,
  'assets.update':               false,
  'assets.archive':              false,
  'reports.read.scan':           true,
  'reports.read.organizational': true,
  'reports.read.executive':      false,
  'reports.read.board':          false,
  'reports.generate':            false,
  'reports.export':              false,
  'exports.create':              false,
  'exports.read':                true,
  'remediation.read':            true,
  'remediation.update':          false,
  'remediation.batches.create':  false,
  'remediation.batches.read':    false,
  'remediation.batches.update':  false,
  'remediation.batches.archive': false,
  'remediation.tasks.read':      true,
  'remediation.tasks.update':    true,
  'remediation.ai_assist':       true,
  'integrations.jira':           false,
  'audit.read':                  true,
  'team.read':                   false,
  'team.invite':                 false,
}

export const PERMISSION_GROUPS: Array<{
  label: string
  permissions: Array<{ key: Permission; label: string }>
}> = [
  {
    label: 'Scans',
    permissions: [
      { key: 'scans.create',  label: 'Create new scans' },
      { key: 'scans.read',    label: 'View scans' },
      { key: 'scans.update',  label: 'Update scan settings' },
      { key: 'scans.archive', label: 'Archive scans' },
    ],
  },
  {
    label: 'Findings',
    permissions: [
      { key: 'findings.read',    label: 'View findings' },
      { key: 'findings.update',  label: 'Update finding status' },
      { key: 'findings.archive', label: 'Archive findings' },
    ],
  },
  {
    label: 'Assets / Inventory',
    permissions: [
      { key: 'assets.create',  label: 'Add new assets' },
      { key: 'assets.read',    label: 'View assets' },
      { key: 'assets.update',  label: 'Update assets' },
      { key: 'assets.archive', label: 'Archive assets' },
    ],
  },
  {
    label: 'Reports',
    permissions: [
      { key: 'reports.read.scan',           label: 'View scan reports' },
      { key: 'reports.read.organizational', label: 'View organisational reports' },
      { key: 'reports.read.executive',      label: 'View executive reports' },
      { key: 'reports.read.board',          label: 'View board reports' },
      { key: 'reports.generate',            label: 'Generate reports' },
      { key: 'reports.export',              label: 'Export reports as PDF' },
    ],
  },
  {
    label: 'Exports',
    permissions: [
      { key: 'exports.create', label: 'Request data exports' },
      { key: 'exports.read',   label: 'View exports' },
    ],
  },
  {
    label: 'Remediation Workflow',
    permissions: [
      { key: 'remediation.read',            label: 'View remediation plans (legacy)' },
      { key: 'remediation.update',          label: 'Update remediation status (legacy)' },
      { key: 'remediation.batches.create',  label: 'Create remediation batches' },
      { key: 'remediation.batches.read',    label: 'View remediation batches' },
      { key: 'remediation.batches.update',  label: 'Edit remediation batches' },
      { key: 'remediation.batches.archive', label: 'Archive remediation batches' },
      { key: 'remediation.tasks.read',      label: 'View assigned remediation tasks' },
      { key: 'remediation.tasks.update',    label: 'Update task status' },
      { key: 'remediation.ai_assist',       label: 'Use AI assist on tasks' },
    ],
  },
  {
    label: 'Integrations',
    permissions: [
      { key: 'integrations.jira', label: 'Configure Jira integration' },
    ],
  },
  {
    label: 'Audit Log',
    permissions: [
      { key: 'audit.read', label: 'View audit log' },
    ],
  },
  {
    label: 'Team',
    permissions: [
      { key: 'team.read',   label: 'View team members' },
      { key: 'team.invite', label: 'Invite new members' },
    ],
  },
]

// Accepts a pre-resolved flat permissions record (from resolvePermissions).
// account_owner callers pass a record of all-true; others pass the output of resolvePermissions().
export function can(
  resolved: Record<Permission, boolean>,
  action: Permission,
): boolean {
  return resolved[action] ?? false
}

export function defaultPermissionsForRole(role: string): Record<Permission, boolean> {
  if (role === 'admin')     return { ...ADMIN_DEFAULTS }
  if (role === 'viewer')    return { ...VIEWER_DEFAULTS }
  if (role === 'developer') return { ...DEVELOPER_DEFAULTS }
  return { ...MEMBER_DEFAULTS }
}
